### PR TITLE
Oceanwater 660 rename faults vars

### PR DESCRIPTION
**Pull request by lanseafood**
## Linked Issues:
| Jira Ticket 🎟️   | [Oceanwater-660](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-660) |
| ----------- | ----------- |
| EPIC ⚡| [Oceanwater-551](urlhttps://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-551) |
| Github :octocat:  | (pre) #98, (sister-in autonomy) https://github.com/nasa/ow_autonomy/pull/35  |

NOTE: Must also pull from OW autonomy PR (linked above)

## Summary of Changes
* renaming and reorganizing names for clarity
* anything remapped stays as is
* `/faults/jpl/` prefix for jpl message topics
* `/faults/trigger` prefix for topics that trigger other node's to take action (ie. power)

## Test
* test build

### CODE REVIEW

**Comment by lanseafood** [comment]
note that it makes more sense to view if you checkout the branch instead of on git, formatting looks a bit weird here.

**Comment by Samahu** [comment]
@lanseafood I will probably hold off reviewing the PR as I do have multiple reserves on the entire approach plus it conflicts with some of the work I have been doing.

**Comment by lanseafood** [comment]
> @lanseafood I will probably hold off reviewing the PR as I do have multiple reserves on the entire approach plus it conflicts with some of the work I have been doing.

@Samahu  this PR is mostly cleanup, or #98 is the main one that's impacting the power Node but I believe it's only the addition of 1 method so let me know if you want to sync to to discuss this since I'm not sure how it would impact the power work you're working on.

**Comment by Samahu** [comment]
> > @lanseafood I will probably hold off reviewing the PR as I do have multiple reserves on the entire approach plus it conflicts with some of the work I have been doing.
> 
> @Samahu this PR is mostly cleanup, or #98 is the main one that's impacting the power Node but I believe it's only the addition of 1 method so let me know if you want to sync to to discuss this since I'm not sure how it would impact the power work you're working on.

Ok, I will approve this and comment on the main the PR since I see part of changes already there

**Review by Samahu — APPROVED** [review]
Approved but see my argument on the use of [`/faults/trigger`]( https://github.com/nasa/ow_simulator/pull/98#issuecomment-820805846) which trigger the whole thing.

**Pull request merged**
