### PR TITLE
changing planner to RRT* for consistent deliver and discard behavior

### PR DESCRIPTION
**Pull request by anjan1984**
## Linked Issues:
| :----------- | :----------- |
| Jira Ticket 🎟️ | [OCEANWATER-932](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-932) |
| Github :octocat:  | # |

## Summary of Changes
* Changed default planner for discard and deliver to RRT* for constant behavior

## Test
*roslaunch ow atacama_y1a.launch 

In a separate terminal :
*./grind_action_client.py 
* ./dig_circular_action_client.py  (you can also use the dig_linear service)
* ./discard_action_client.py
*  ./dig_circular_action_client.py (you can also use the dig_linear service)
* ./deliver_action_client.py

### CODE REVIEW

**Comment by kmdalal** [comment]
This fixes the problem, but takes us back to where we were, with the much slower planner.   Is it possible to add constraints in the other planner, such as that the scoop never tilts sideways?  This might correct the bad movements.

**Comment by anjan1984** [comment]
> This fixes the problem, but takes us back to where we were, with the much slower planner. Is it possible to add constraints in the other planner, such as that the scoop never tilts sideways? This might correct the bad movements.

I had tried to use constrained planning before... Had mixed success with it. RRT* gave much robust solutions.

**Review by kmdalal — APPROVED** [review]
Per discussion today, performance improvement can be future work.

**Comment by AstroStucky** [comment]
The additional time RRT* requires for planning had to be accounted for in the deliver and discard max durations in the terrain_interaction test, so I went ahead and added a commit for that. This change requires no additional testing from reviewers.

**Comment by AstroStucky** [comment]
The prescribed test passes for me, and I performed the terrain_interaction test 3 times with no failures.

**Pull request merged**
