### PR TITLE
updated power profiles

### PR DESCRIPTION
**Pull request by lanseafood**
## Linked Issues:
| Jira Ticket 🎟️   | [Oceanwater-XXX](url) |
| ----------- | ----------- |
| EPIC ⚡| [Oceanwater-XXX](url) |
| Github :octocat:  | # |

## Summary of Changes
* updated soc and cap loss. These are the full files and will take 700s+ to find final faults. 
* battery temp file added, you will only need to wait a few seconds for this fault to occur. 

## Test
*

### CODE REVIEW

**Review by kmdalal — CHANGES_REQUESTED** [review]
These profiles did not resolve the key problem, which is the failure of test 6.2.5.  Please substitute the newer profiles from Chetan.

**Comment by lanseafood** [comment]
> These profiles did not resolve the key problem, which is the failure of test 6.2.5. Please substitute the newer profiles from Chetan.

@kmdalal as Chetan mentioned, he hasn't yet created the thermal power files. He's only generated the two soc faults so far, which are these.

**Comment by kmdalal** [comment]
@lanseafood , I was referring to the new profiles that Chetan emailed to us around 3pm yesterday, where he claims that the temperature hits threshold before SOC.  He included plots.  I have not looked at these files.

**Comment by lanseafood** [comment]
OK, then I'll edit this PR to include the thermal since this PR was meant
to just update the low soc and cap loss as titled.


Lanssie Mingyue Ma
U.C. Berkeley B.A. Computer Science
Georgia Tech M.S. CSE
Georgia Tech Ph.D. CSE/AE

**Comment by kmdalal** [comment]
> OK, then I'll edit this PR to include the thermal since this PR was meant to just update the low soc and cap loss as titled.

The intention of this PR (as I understood it) was to address failing test 6.5.2, whatever that entails.  Retitling is fine, but adding the new profiles is totally within scope.

**Comment by lanseafood** [comment]
temp added as well

**Review by kmdalal — APPROVED** [review]
Satisfactory for Release 8, though thermal fault erratic behavior logged in Jira OCEANWATER-679.

**Pull request merged**
