### PR TITLE
Oceanwater 555 fix black image with lens flare

### PR DESCRIPTION
**Pull request by mogumbo**
## Linked Issues:
| EPIC ⚡ | [OCEANWATER-86](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-86) |
| :----------- | :----------- |
| Jira Ticket 🎟️ | [OCEANWATER-555](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-555) |
| Github :octocat:  | # |

## Summary of Changes
* Subclassed gazebo's LensFlareSensorPlugin to allow color to be set in real-time.
* Set exact sun color (the brightness is the important part) using sunlight_values_for_shaders.py
* Specify compositor CameraLensFlare/PF_FLOAT32_R to be used by the plugin because it uses a floating point intermediate texture, necessary for our floating point shading pipeline.

## Test
* roslaunch ow europa_terminator.launch
* In rqt check checkboxes /ant_pan_position_controller/command, /ant_tilt_position_controller/command, and /StereoCamera/left/image_trigger
* Expand the pan and tilt topics to reveal their data settings.
* Set pan = 1.2 and tilt = -0.15
* Observe in rqt's Image View widget that you can see the terrain, the sun, and the lens flare all at the same time.

### CODE REVIEW

**Comment by Samahu** [comment]
Sorry @mogumbo but I am running a bit short on time and wouldn't be able to suffice as a reviewer on this PR.

**Comment by AstroStucky** [comment]
I'm seeing the following build error
```
Starting  >>> ow_gazebo_plugins                                                                                                        
_______________________________________________________________________________________________________________________________________
Errors     << ow_gazebo_plugins:cmake /home/starry/oceanwaters/workspace/logs/ow_gazebo_plugins/build.cmake.000.log                    
CMake Error at /home/starry/oceanwaters/workspace/src/ow_simulator/ow_gazebo_plugins/src/OWLensFlareSensorPlugin/CMakeLists.txt:23 (string):
  string sub-command REPLACE requires at least four arguments.


cd /home/starry/oceanwaters/workspace/build/ow_gazebo_plugins; catkin build --get-env ow_gazebo_plugins | catkin env -si  /usr/bin/cmake /home/starry/oceanwaters/workspace/src/ow_simulator/ow_gazebo_plugins --no-warn-unused-cli -DCATKIN_DEVEL_PREFIX=/home/starry/oceanwaters/workspace/devel/.private/ow_gazebo_plugins -DCMAKE_INSTALL_PREFIX=/home/starry/oceanwaters/workspace/install; cd -

.......................................................................................................................................
Failed     << ow_gazebo_plugins:cmake                [ Exited with code 1 ]                                                            
Failed    <<< ow_gazebo_plugins                      [ 4.6 seconds ]  
```
This was following `catkin clean` and a `source /opt/ros/noetic/setup.bash` in a fresh terminal.

**Comment by mogumbo** [comment]
The cmake error is probably because you don't haven't done `source /usr/share/gazebo/setup.sh` when setting up your compile shell. Sourcing gazebo has always been "required", but it was never really necessary for ROS1 (it did become necessary for building ROS2 sims). I'll have to think a little more about what is the best solution here.

**Comment by AstroStucky** [comment]
> The cmake error is probably because you don't haven't done `source /usr/share/gazebo/setup.sh` when setting up your compile shell. Sourcing gazebo has always been "required", but it was never really necessary for ROS1 (it did become necessary for building ROS2 sims). I'll have to think a little more about what is the best solution here.

This turns out to be the problem. It's compiled now. I'll comment with test results in a bit.

**Review by AstroStucky — APPROVED** [review]
Test worked great. No comments on code. Approved!

Our lander could use some shades now :sunglasses: 
lensflare

**Comment by AstroStucky** [comment]
The missing GAZEBO_PLUGIN_PATH error message that was just added works for me.

**Review by anjan1984 — APPROVED** [review]

**Comment by AstroStucky** [comment]
`GAZEBO_PLUGIN_PATH` is now found without having to `/usr/share/gazebo/setup.sh` prior to compiling. Reran the test too, and it work fine.

**Comment by anjan1984** [comment]
Retested and working fine!

**Pull request merged**
