### PR TITLE
remove rviz visualization of planned path

### PR DESCRIPTION
**Pull request by anjan1984**
## Linked Issues:
| EPIC ⚡| [OCEANWATER-XXX](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-XXX) |
) |
| :----------- | :----------- |
| Jira Ticket 🎟️   | [OCEANWATER-XXX](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-XXX)) |
| Github :octocat:  | # |

## Summary of Changes
* Removes Rviz Visualization of the plans. (Turns out it was not the fake controller but Rviz was showing the planned path.)

## Test
* Run any Ros action to see no displayed rviz trjactory before movement of Gazebo

### CODE REVIEW

**Comment by kmdalal** [comment]
This works as advertised, but does not address the serious problem of the _delay_ between when the action is activated (goal sent) and the actual arm movement starting.  This can take up to 30 seconds.  Is the planning algorithm really taking that long?  If so, then it's better to visualize the planning like before, because now both Rviz and Gazebo are still and one wonders what's going on.

**Comment by anjan1984** [comment]
Yes .. it will take that time... Might improve a little bit, now  that RRT outputs are not displayed ... Best not to merge this then....

**Comment by Samahu** [comment]
Based on the feedback from @mikedalal this doesn't seem to help improve the execution speed of arm operations. If that's the case then I would suggest closing this PR.

**Comment by kmdalal** [comment]
> Based on the feedback from @mikedalal this PR doesn't seem to help improve the execution speed of arm operations. If that's the case then I would suggest closing it.

This has been agreed on by the team, so closing for now.

**Pull request closed without merging**
