### PR TITLE
 making planner rrt star for guarded move for consistant planning

### PR DESCRIPTION
**Pull request by anjan1984**
## Linked Issues:
| :----------- | :----------- |
| Jira Ticket 🎟️ | [OCEANWATER-1046](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-1046) |
| Github :octocat:  | # |

## Summary of Changes
* changing guarded move planner to rrt star for consistent paths 

## Test
* roslaunch ow atacama_y1a.launch

Tests: 

cd ow_simulator/ow_lander/scripts

./guarded_move_action_client.py 1.7 0.3 0.5 0 0 1 0.7
./guarded_move_action_client.py 1.7 -0.3 0.5 0 0 1 0.7
./guarded_move_action_client.py 1.9 -0.4 0.5 0 0 1 0.7
./guarded_move_action_client.py 1.9 0.5 0.5 0 0 1 0.7
./guarded_move_action_client.py 1.7 0.0 0.5 1 1 1 0.7
./guarded_move_action_client.py 1.7 0.0 0.5 0.5 -0.5 1 0.8 
./guarded_move_action_client.py 1.78 -0.20 -0.12 0.00 0.00 1.00 0.50
./guarded_move_action_client.py 1.5 -0.20 -0.12 0.00 0.00 1.00 0.50
--

### CODE REVIEW

**Comment by kmdalal** [comment]
The following attempt was successful but ended with a Python error we see occasionally from the lander scripts -- it would be good to track down and fix that problem (as a separate Jira if neede).
```
$ ./guarded_move_action_client.py 1.7 0.0 0.5 1 1 1 0.7
[INFO]: Requested x_start value: 1.7
[INFO]: Requested y_start value: 0.0
[INFO]: Requested z_start value: 0.5
[INFO]: Requested direction_x value: 1.0
[INFO]: Requested direction_y value: 1.0
[INFO]: Requested direction_z value: 1.0
[INFO]: Requested search_distance value: 0.7
[INFO]: Result: final: 
  x: 1.391297134375944
  y: -0.73551796776681
  z: -0.10884827036615119
success: True
Exception in thread /GuardedMove/feedback:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_pubsub.py", line 185, in robust_connect_subscriber
    conn.receive_loop(receive_cb)           
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 846, in receive_loop
    self.close()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 858, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'
```

**Comment by kmdalal** [comment]
The previous error occurred again for `./guarded_move_action_client.py 1.7 0.0 0.5 0.5 -0.5 1 0.8` but is not reproducible -- it just happens sometimes.

**Review by kmdalal — APPROVED** [review]
I tried the given tests plus several more, including a full run of ReferenceMission1.  They all worked, with a few occurrences of the Python error at the end that I have reported.  (Separate problem since it occurs with other action client scripts).

This isn't really a satisfactory "fix" because it reverts us to the previous planner which is very slow.  But we can do with this for Release 10 and then revisit performance improvement.

**Comment by anjan1984** [comment]
Created a separate ticket for threading issue 
https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-1059

**Pull request merged**
