### PR TITLE
A sample dock that can hold collected samples

### PR DESCRIPTION
**Pull request by Samahu**
## Linked Issues:
| EPIC ⚡| [OCEANWATER-680 / Sample Acquisition ](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-680) |
| :----------- | :----------- |
| Jira Ticket 🎟️   | [OCEANWATER-710 / Adjust sample dock to hold collected samples](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-710)) |
| Github :octocat:  | N/A |

## Summary of Changes
* Added a sample dock that can hold collected samples
* Adjusted inertia values accordingly

image

## Test
* Run a sample collection procedure that dumps collected into the sample dock
* The sample dock should keep hold of the collected sample

### CODE REVIEW

**Review by AstroStucky — APPROVED** [review]
It seems to hold whatever I drop in it. The sample delivery command does not reliably deliver material directly over the dock each time, but this is separate issue for separate PR.

**Comment by kmdalal** [comment]
> It seems to hold whatever I drop in it. The sample delivery command does not reliably deliver material directly over the dock each time, but this is separate issue for separate PR.

Does this branch include the latest melodic-devel, and did arm operations work okay?  (I'm referring to the problem reported on Teams/General this hour).  I'm wondering if the sample delivery problem is related.

**Comment by Samahu** [comment]
> > It seems to hold whatever I drop in it. The sample delivery command does not reliably deliver material directly over the dock each time, but this is separate issue for separate PR.
> 
> Does this branch include the latest melodic-devel, and did arm operations work okay? (I'm referring to the problem reported on Teams/General this hour). I'm wondering if the sample delivery problem is related.

The stated problem is outside the scope of this PR.

**Comment by Samahu** [comment]
I went ahead and merged the PR without Anjan's approval since he is busy with another higher priority ticket.

**Pull request merged**
