### PR TITLE
Hotfix/oceanwater 823 apply material to samples

### PR DESCRIPTION
**Pull request by mogumbo**
## Linked Issues:
| EPIC ⚡ | [OCEANWATER-680](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-680) |
| :----------- | :----------- |
| Jira Ticket 🎟️ | [OCEANWATER-823](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-823) |
| Github :octocat:  | # |

## Summary of Changes
* Added material colors and shaders to ow_regolith models.
* Removed unused model.

## Test
* Run the first 3 steps of https://babelfish.arc.nasa.gov/confluence/display/OCEANWATERS/OW-TEST-009-7+Terrain+Visual+Feedback
* (In this test it appears as if the samples don't obey gravity and fall to the wrong sides of the scoop. This may be a problem for a separate ticket.)
or
* roslaunch ow atacama_y1a.launch
* cd src/ow_simulator/ow_regolith/scripts
* ./spawn_bulk_sample.sh ../rsdf/ball_sand.rsdf 0.02 10  (or use one of the other rsdf models)

### CODE REVIEW

**Review by Samahu — APPROVED** [review]
I can observe the material applied to the samples as described:
image
This is probably sufficient for now, for next release we may want to trace the color of the terrain where the scoop interacts with the terrain and apply a material to the collected samples that have good representation of these traced colors.

**Review by AstroStucky — APPROVED** [review]
Test works. I like that you've colorized the models for their material 👍

**Comment by AstroStucky** [comment]
> (In this test it appears as if the samples don't obey gravity and fall to the wrong sides of the scoop. This may be a problem for a separate ticket.)

Their disobedience towards gravity is by design. Each model has a minimal force applied to it from the time it is spawned to the end of a dig action in order to keep them in the scoop. 

But maybe I misunderstood because I'm not sure what you mean "fall to the wrong sides of the scoop"? Could you show an example?

**Comment by mogumbo** [comment]
> Their disobedience towards gravity is by design. Each model has a minimal force applied to it from the time it is spawned to the end of a dig action in order to keep them in the scoop.

Okay. I think that's what I'm seeing.

**Pull request merged**
