### PR TITLE
Removed expected_final checks

### PR DESCRIPTION
**Pull request by AstroStucky**
## Linked Issues:
| EPIC ⚡ | |
| :----------- | :----------- |
| Jira Ticket 🎟️ | [OCEANWATER-1038](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-1038) |
| Github :octocat:  | # |

## Purpose
The test would sporadically fail due to comparing the final position of each arm action with a hard coded position. The tolerance was set fairly high, but these checks would still sporadically fail. Since these checks are redundant to with the arm_check_action.py rostest, it seems best to just simply remove the checks, so that test maintenance effort doesn't have to be duplicated. 

## Summary of Changes
* Removed the expected_final checks from `terrain_interaction.py`

## Test
Run the test `rostest ow_sim_tests terrain_interaction.test`
Hopefully everything passes, but there is one more sporadic failure where regolith jumps out of the sample dock, and if that occurs it will typically fail either tests 6 or 8. If this occurs, just ignore it. This problem is already captured by [OCEANWATER-1039](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-1039)

### CODE REVIEW

**Comment by anjan1984** [comment]
I am getting an error when I run the test 

rostest ow_sim_tests terrain_interaction.py     
... logging to /home/achakra2/.ros/log/rostest-tron.ndc.nasa.gov-60339.log
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/roslaunch/xmlloader.py", line 739, in _parse_launch
    root = parse(filename).getElementsByTagName('launch')
  File "/usr/lib/python3.8/xml/dom/minidom.py", line 1959, in parse
    return expatbuilder.parse(file)
  File "/usr/lib/python3.8/xml/dom/expatbuilder.py", line 911, in parse
    result = builder.parseFile(fp)
  File "/usr/lib/python3.8/xml/dom/expatbuilder.py", line 207, in parseFile
    parser.Parse(buffer, 0)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/roslaunch/config.py", line 461, in load_config_default
    loader.load(f, config, argv=args, verbose=verbose)
  File "/opt/ros/noetic/lib/python3/dist-packages/roslaunch/xmlloader.py", line 759, in load
    launch = self._parse_launch(filename, verbose)
  File "/opt/ros/noetic/lib/python3/dist-packages/roslaunch/xmlloader.py", line 741, in _parse_launch
    raise XmlParseException("Invalid roslaunch XML syntax: %s"%e)
roslaunch.xmlloader.XmlParseException: Invalid roslaunch XML syntax: not well-formed (invalid token): line 1, column 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/ros/noetic/bin/rostest", line 71, in <module>
    rostestmain()
  File "/opt/ros/noetic/lib/python3/dist-packages/rostest/__init__.py", line 279, in rostestmain
    _main()
  File "/opt/ros/noetic/lib/python3/dist-packages/rostest/rostest_main.py", line 159, in rostestmain
    testCase = rostest.runner.createUnitTest(pkg, test_file, options.reuse_master, options.clear, options.results_base_dir)
  File "/opt/ros/noetic/lib/python3/dist-packages/rostest/runner.py", line 229, in createUnitTest
    config = roslaunch.parent.load_config_default([test_file], None)
  File "/opt/ros/noetic/lib/python3/dist-packages/roslaunch/config.py", line 463, in load_config_default
    raise RLException(e)
roslaunch.core.RLException: Invalid roslaunch XML syntax: not well-formed (invalid token): line 1, column 1

**Comment by AstroStucky** [comment]
@anjan1984 I'm not seeing enough output here to determine what's the cause. Could you please provide the entire log of the test run? I've seen failing rostest produce an awful lot of extraneous error messages, and I suspect there is a more root cause that's not shown in what you posted.

**Comment by anjan1984** [comment]
Sorry the instructions should have been rostest ow_sim_tests terrain_interaction.test

Discard and Dig_circular are failing. I have tried the tests 3 times

**Comment by AstroStucky** [comment]
I've fixed the testing procedure. 
@anjan1984 Could you provide the logs for those failures?

**Comment by anjan1984** [comment]
> rostest ow_sim_tests terrain_interaction.test

ROSTEST]-----------------------------------------------------------------------

[ow_sim_tests.rosunit-terrain_interaction/test_01_unstow][passed]
[ow_sim_tests.rosunit-terrain_interaction/test_02_grind][passed]
[ow_sim_tests.rosunit-terrain_interaction/test_03_dig_linear][passed]
[ow_sim_tests.rosunit-terrain_interaction/test_04_discard][FAILURE]-------------
True is not false : Regolith models spawned at wrong time!
  File "/usr/lib/python3.8/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib/python3.8/unittest/case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "/usr/lib/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "/usr/local/home/achakra2/oceanwaters_ws/src/ow_simulator/ow_sim_tests/test/terrain_interaction.py", line 411, in test_04_discard
    self._assert_regolith_not_present()
  File "/usr/local/home/achakra2/oceanwaters_ws/src/ow_simulator/ow_sim_tests/test/terrain_interaction.py", line 116, in _assert_regolith_not_present
    self.assertFalse(
  File "/usr/lib/python3.8/unittest/case.py", line 759, in assertFalse
    raise self.failureException(msg)
--------------------------------------------------------------------------------

[ow_sim_tests.rosunit-terrain_interaction/test_05_dig_circular][FAILURE]--------
0.863210546764631 not less than or equal to 0.12 : Regolith fell out of scoop!
regolith name     : regolith_0::link
regolith position : (1.81, 0.86, -7.45)
scoop position    : (1.50, 0.86, -6.64)
  File "/usr/lib/python3.8/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib/python3.8/unittest/case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "/usr/lib/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "/usr/local/home/achakra2/oceanwaters_ws/src/ow_simulator/ow_sim_tests/test/terrain_interaction.py", line 422, in test_05_dig_circular
    dig_circular_result = self._test_action(
  File "/usr/local/home/achakra2/oceanwaters_ws/src/ow_simulator/ow_sim_tests/test/terrain_interaction.py", line 290, in _test_action
    action_fail_condition()
  File "/usr/local/home/achakra2/oceanwaters_ws/src/ow_simulator/ow_sim_tests/test/terrain_interaction.py", line 171, in _assert_scoop_regolith_containment
    assert_func(
  File "/usr/local/home/achakra2/oceanwaters_ws/src/ow_simulator/ow_sim_tests/test/terrain_interaction.py", line 139, in _assert_point_is_near
    self.assertLessEqual(distance(p1, p2), delta, msg)
  File "/usr/lib/python3.8/unittest/case.py", line 1304, in assertLessEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/usr/lib/python3.8/unittest/case.py", line 753, in fail
    raise self.failureException(msg)
--------------------------------------------------------------------------------

[ow_sim_tests.rosunit-terrain_interaction/test_06_deliver][passed]
[ow_sim_tests.rosunit-terrain_interaction/test_07_stow][FAILURE]----------------
30.102499961853027 not less than 30.0 : Timeout reached waiting for Unstow action to finish!
  File "/usr/lib/python3.8/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib/python3.8/unittest/case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "/usr/lib/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "/usr/local/home/achakra2/oceanwaters_ws/src/ow_simulator/ow_sim_tests/test/terrain_interaction.py", line 469, in test_07_stow
    self.test_01_unstow()
  File "/usr/local/home/achakra2/oceanwaters_ws/src/ow_simulator/ow_sim_tests/test/terrain_interaction.py", line 325, in test_01_unstow
    unstow_result = self._test_action(
  File "/usr/local/home/achakra2/oceanwaters_ws/src/ow_simulator/ow_sim_tests/test/terrain_interaction.py", line 294, in _test_action
    self.assertLess(
  File "/usr/lib/python3.8/unittest/case.py", line 1298, in assertLess
    self.fail(self._formatMessage(msg, standardMsg))
  File "/usr/lib/python3.8/unittest/case.py", line 753, in fail
    raise self.failureException(msg)
--------------------------------------------------------------------------------

[ow_sim_tests.rosunit-terrain_interaction/test_08_ingest_sample][passed]

SUMMARY
 * RESULT: FAIL
 * TESTS: 8
 * ERRORS: 0
 * FAILURES: 3

**Comment by AstroStucky** [comment]
Closing this in favor of rolling these changes in with a future PR that will include more substantial fixes to the terrain interaction test, and possibly other automated tests. Thank you for your testing and comments, Anjan.

**Pull request closed without merging**
