### PR TITLE
Oceanwater 833 update moveit syntax for noetic

### PR DESCRIPTION
**Pull request by mogumbo**
## Linked Issues:
| Jira Ticket 🎟️ | [OCEANWATER-833](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-833) |

## Summary of Changes
* Simple changes to update to noetic moveit API

## Test
* Ensure that ow_autonomy is on branch noetic-devel
* roslaunch ow atacama_y1a.launch
* roslaunch ow_plexil ow_exec.launch plan:=ReferenceMission1.plx
* ReferenceMission1 will fail on just about everything without these changes. It should succeed with them.

### CODE REVIEW

**Comment by kmdalal** [comment]
I'm unable to test this, as I don't have Noetic up yet.  The code changes look harmless, though I'm not strong in Python.

**Comment by Samahu** [comment]
The action server loads successfully but I have two actions (`dig_linear_action_client.py` + `dig_circular_action_client.py`) that are not working and I get this error message:
`Fail: ABORTED: No motion plan found. No execution attempted.`

**Comment by Samahu** [comment]
> The action server loads successfully but I have two actions (`dig_linear_action_client.py` + `dig_circular_action_client.py`) that are not working and I get this error message: `Fail: ABORTED: No motion plan found. No execution attempted.`

Even `stow_action_client.py` doesn't work

**Comment by mogumbo** [comment]
Closing this PR. It's changes are included in https://github.com/nasa/ow_simulator/pull/189

**Pull request closed without merging**
