### PR TITLE
Oceanwater 614 implement a force torque sensor for the lander arm

### PR DESCRIPTION
**Pull request by Samahu**
## Linked Issues:
| EPIC ⚡| [OCEANWATER-614 / Implement a force torque sensor for the lander arm ](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-614) |
| :----------- | :----------- |
| Jira Ticket 🎟️   | ~[OCEANWATER-615 / Introduce a force torque sensor for the dist_patch joint ](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-615)~ |
| Jira Ticket 🎟️   | ~[OCEANWATER-616 / Implement guarded move using the ft sensor ](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-616)~ |
| Jira Ticket 🎟️   | ~[OCEANWATER-617 / Introduce sufficient noise to model a realistic sensor ](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-617)~ |
| Jira Ticket 🎟️   | ~[OCEANWATER-618 / Model potential faults or failure for the ft sensor ](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-618)~ |
| Jira Ticket 🎟️   | ~[OCEANWATER-619 / Update the user guide to include utilization of the FT Sensor ](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-619)~ |
| Jira Ticket 🎟️   | [OCEANWATER-620 / Document sensor response when loading a sample with varying mass into scoop ](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-620) [DESCOPED] |
| Jira Ticket 🎟️   | [OCEANWATER-646 / Model FT sensor drift ](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-646) [DESCOPED] |
| Jira Ticket 🎟️   | [OCEANWATER-647 / Increased noise of ft sensor in correlation with certain events ](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-647) [DESCOPED] |
| Github :octocat:  | #94, #96, #106, #109, #110 |

## Summary of Changes
* Introduced a force torque sensor for the **dist_patch** joint (highlighted below in red)
image
* Implement guarded move using readings of the ft sensor
  - Removed the old method
* Set FT sensor update rate to 200 Hz
  - Note that the [Barret FT sensor](https://web.barrett.com/files/Low-Profile_Force-Torque_Sensor_FT-02-2011.pdf) runs at 250 Hz by default and has a maximum update rate of 2500 Hz. However, the **gazebo_ros_ft_sensor** is only able to provide a maximum update rate of 200 Hz. 
* Set sensor Gaussian noise value to 0.2
  - Noise value is based on generated noise profile of the [Barret FT sensor](https://web.barrett.com/files/Low-Profile_Force-Torque_Sensor_FT-02-2011.pdf)

| Barret FT Sensor Noise | Simulated FT Sensor Noise |
| :----------: | :----------: |
|image|image|
|image|image|
* Modeled three types of faults for the ft_sensor
  - zero signal
  - signal bias
  - increase signal noise

| Fault | Signal |
| :----------- | :----------- |
| Zero Signal |image|
| Signal Bias |image|
| Increased Signal Noise |image|

## Test
 1) Launch the simulation
```bash
roslaunch ow (atacma_y1a.launch | europa_terminator_workspace.launch)
```
2) While the simulation running open another terminal and use rostopic to listen to the **ft_sensor_dist_pitch** topic
```bash
rostopic echo /ft_sensor_dist_pitch
```
* You should see a stream of **geometry_msgs/WrenchStamped** messages with relatively stable values for force and torque.
3) Execute any arm activity and you should see the stream of values fluctuate.

4) While the simulation running invoke guarded move with varying set of valid arguments in the same session.
```bash
rosservice call /arm/guarded_move -- True 0 0 0 0 0 0 0
rosservice call /arm/guarded_move -- False 1.7 0.3 0.5 0 0 1 0.7
rosservice call /arm/guarded_move -- False 1.7 -0.3 0.5 0 0 1 0.7
rosservice call /arm/guarded_move -- False 1.9 -0.4 0.5 0 0 1 0.7
rosservice call /arm/guarded_move -- False 1.9 0.5 0.5 0 0 1 0.7
rosservice call /arm/guarded_move -- False 1.7 0.0 0.5 1 1 1 0.7
rosservice call /arm/guarded_move -- False 1.7 0.0 0.5 0.5 -0.5 1 0.8
```
The ground is detected with no delay or premature detection.

5) Use the **dyanmic_reconfigure** UI to apply any of the three faults (zero signal, signal bias, increase signal noise) and see the signal changes as shown the faults table mentioned earlier
image
>Note: you can apply them individually or in combination

### CODE REVIEW

**Comment by Samahu** [comment]
List of changes that hasn't been reviewed in any of the related PRs:
* Set sensor update rate to 200 Hz
* Resolved build conflict between ft_sensor branch and melodic-devel
* Added a [new test case for the FT sensor](https://babelfish.arc.nasa.gov/confluence/display/OCEANWATERS/OW-TEST008+-+release-8-0)

**Comment by Samahu** [comment]
> List of changes that hasn't been reviewed in any of the related PRs:
> 
> * Set sensor update rate to 200 Hz
> * Resolved build conflict between ft_sensor branch and melodic-devel
> * Added a [new test case for the FT sensor](https://babelfish.arc.nasa.gov/confluence/display/OCEANWATERS/OW-TEST008+-+release-8-0)

@mikedalal @lanseafood @mogumbo  No need to spend too much on it since most of this PR has already been reviewed .. maybe make sure the branch compiles successfully and take a look at the test case and if it is missing certain verification steps.

**Comment by Samahu** [comment]
I'll merge the PR into melodic-devel once I have two approvals

**Review by lanseafood — APPROVED** [review]
Went through all the tests, seems to be working for everything! Whoo!

Occasionally I see this output below, but I've also seen that randomly throughout OW before so I don't think it from anything in this PR.
`ODE Message 3: LCP internal error, s <= 0 (s=-3.8069e+10)
`

**Review by kmdalal — COMMENTED** [review]
Tried several GuardedMoves, experimented with fault settings, looks good!

**Review by kmdalal — APPROVED** [review]

**Pull request merged**
