### PR TITLE
Add bulk sample spawner script

### PR DESCRIPTION
**Pull request by AstroStucky**
## Linked Issues:
| EPIC ⚡| [OCEANWATER-680](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-680) |
| :----------- | :----------- |
| Jira Ticket 🎟️   | [OCEANWATER-713](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-713) |
| Github :octocat:  | na |

## Summary of Changes
* Added a script for spawning bulk material into the Gazebo sim.
* Added two directories to the ow directory: rsdf and scripts. rsdf contains Embedded Ruby SDF files that the new script uses.

## Test
1. Launch the europa_terminator_workspace world 
`roslaunch ow europa_terminator_workspace.launch`
2. Now we need to get the scoop in an upward facing position ready to receive sample dropped into it. The easiest way to do this is to call dig circular and wait for it to finish. The dig circular does not need to touch the ground, and likely won't in this world.
`rosservice call /arm/dig_circular True 0 0 0 False 0`
3. Try spawning some sample
`src/ow_simulator/ow/scripts/spawn_bulk_sample.sh src/ow_simulator/ow/rsdf/ball_icefrag.rsdf 0.05 5`

### --test flag example
Feel free to play around with the different command arguments if you'd like, but before running the script with new arguments  always check how many spawns those arguments will result in by using the `--test` flag as the final argument. Here's an example:
```
$ src/ow_simulator/ow/scripts/spawn_bulk_sample.sh src/ow_simulator/ow/rsdf/ball_snow.rsdf 0.01 5 --test
Bulk material properties specified from ................. src/ow_simulator/ow/rsdf/ball_snow.rsdf
Target mass is .......................................... 5 kg
Model diameter (size) is ................................ 0.01 m
Mass per model is ....................................... 0.031415926535897934 kg
Total models that will spawn is ......................... 159
Totaling to a mass of ................................... 4.995132 kg
This total mass value differs from the target mass by ... -0.004868 kg
This is just a test. Skipping particle spawn step.
```
159 is too many! Revise your arguments and try again.

### CODE REVIEW

**Comment by Samahu** [comment]
Added @lanseafood to the PR. Maybe that can help her think ahead about faults for samples and such

**Comment by kmdalal** [comment]
After many attempts, the dig_circular always fails, leaving the scoop facing the ground.  These warnings:
```
[ WARN]: Controller limbs_controller failed with error PATH_TOLERANCE_VIOLATED: 
[ WARN]: Controller handle limbs_controller reports status ABORTED
```
are later followed by this error:
```
[ERROR]: 
Invalid Trajectory: start point deviates from current robot state more than 0.02
joint 'j_dist_pitch': expected: 0.366833, current: 0.466058
```

**Comment by AstroStucky** [comment]
> After many attempts, the dig_circular always fails, leaving the scoop facing the ground. These warnings:

I admit, I encountered this problem myself, but it wasn't at all clear why since the branch it's based on did not exhibit the problem. Since the arm issues seemed to behave differently depending on the user's MoveIt version, I figured I'd submit the PR anyways and see what happens for others.

Lets hold off on testing this branch for now until PR#151 is approved and merged into melodic-devel, which is sounding like will fix the arm issues you experienced. PR#151 is merged I will merge meldoic-devel into this branch, and testing can resume.

**Comment by Samahu** [comment]
> After many attempts, the dig_circular always fails, leaving the scoop facing the ground. These warnings:
> 
> ```
> [ WARN]: Controller limbs_controller failed with error PATH_TOLERANCE_VIOLATED: 
> [ WARN]: Controller handle limbs_controller reports status ABORTED
> ```
> 
> are later followed by this error:
> 
> ```
> [ERROR]: 
> Invalid Trajectory: start point deviates from current robot state more than 0.02
> joint 'j_dist_pitch': expected: 0.366833, current: 0.466058
> ```
> 
> I'm using the Atacama world.

I think this issue is outside the scope for this PR. I am testing with **europa_terminator_workspace** and the script spawn the beads as expected

**Comment by Samahu** [comment]
It is cool to see that some of the ball beads made it to the newly renovated sample holder :partying_face: :
image

**Comment by Samahu** [comment]
@AstroStucky Couldn't you do everything with `awk` only?

**Comment by AstroStucky** [comment]
> @AstroStucky Couldn't you do everything with `awk` only?

Could you elaborate? Do you mean I could do the `erb` step in `awk`? If that's true, I'm not familiar enough with `awk` to know how.

**Comment by Samahu** [comment]
> > @AstroStucky Couldn't you do everything with `awk` only?
> 
> Could you elaborate? Do you mean I could do the `erb` step in `awk`? If that's true, I'm not familiar enough with `awk` to know how.

`awk` and `sed` are standard for pretty much any linux distrbution (for string replacement). I don't feel strongly against using ruby but this would let us avoid having another dependency.

**Review by Samahu — APPROVED** [review]
Good work!

**Comment by kmdalal** [comment]
@AstroStucky , this branch needs melodic-devel merged into it, so that it gets the recent hotfix.  Please do that and I'll retest.

**Comment by AstroStucky** [comment]
> @AstroStucky , this branch needs melodic-devel merged into it, so that it gets the recent hotfix. Please do that and I'll retest.

melodic-devel is now merged. Note that the testing procedure has been revised to now request that you launch europa_terminator_workspace. Please let me know how it goes.

**Review by kmdalal — APPROVED** [review]
Works well.   Nice addition!

**Pull request merged**
