### PR TITLE
Lander Xacro File Tuning

### PR DESCRIPTION
**Pull request by Samahu**
Damaina, these are the changes you made to melodic-devel as part of the speed up I think. Do you think these make sense as part of OCENWATER-518.

I left them unmerged yet to give you the ability to compare

### CODE REVIEW

**Comment by damianacatanoso** [comment]
With or without merging this values in OW-518, this branch experiences LCP errors, not only during the scoop-ground contact, but always, even when the arm is stowed. I opened https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-566 to re-tune sim stability parameters such as kp, kd, damping.

**Comment by Samahu** [comment]
> With or without merging this values in OW-518, this branch experiences LCP errors, not only during the scoop-ground contact, but always, even when the arm is stowed. I opened https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-566 to re-tune sim stability parameters such as kp, kd, damping.

I started noticing the LCP errors after I have synchronized OCEANWATER-518 with melodic-devel. Most of the changes were Faults related and of the merged I left out the `lander.xacro` to minimize the issue.

**Comment by Samahu** [comment]
> > With or without merging this values in OW-518, this branch experiences LCP errors, not only during the scoop-ground contact, but always, even when the arm is stowed. I opened https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-566 to re-tune sim stability parameters such as kp, kd, damping.
> 
> I started noticing the LCP errors after I have synchronized OCEANWATER-518 with melodic-devel. Most of the changes were Faults related, during the synchronization I left out `lander.xacro` to minimize the issue.

I take that back.. the LCP error were existing the branch before the merge .. I am not at what point these got introduced though .. I was noticing them that much before.

**Comment by damianacatanoso** [comment]
> > > With or without merging this values in OW-518, this branch experiences LCP errors, not only during the scoop-ground contact, but always, even when the arm is stowed. I opened https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-566 to re-tune sim stability parameters such as kp, kd, damping.
> > 
> > 
> > I started noticing the LCP errors after I have synchronized OCEANWATER-518 with melodic-devel. Most of the changes were Faults related, during the synchronization I left out `lander.xacro` to minimize the issue.
> 
> I take that back.. the LCP error were existing the branch before the merge .. I am not at what point these got introduced though .. I was noticing them that much before.

We can definitely silence them but this doesn't solve the problem. If the errors appear it means that there's something wrong with the stability of some of the contacts. Proper tuning of kp, kd, damping can stabilize contacts and eliminate the error to the root.

**Review by damianacatanoso — APPROVED** [review]

**Pull request merged**
