### PR TITLE
HOTFIX/OceanWATERS-847: Resolve warning could not fill color channel of point cloud

### PR DESCRIPTION
**Pull request by Samahu**
## Linked Issues:
| EPIC ⚡ | N/A |
| :----------- | :----------- |
| Jira Ticket 🎟️ | [OCEANWATER-847 / Resolve the warning message "Could not fill color channel of the point cloud, unsupported encoding 'rgb16'"](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-847) |
| Github :octocat:  | N/A |

## Summary of Changes
* Update the output format of the stereo camera to match the formats supported by stereo_image_proc node
* The generate point cloud now correctly displays colors:

| Before Fix | After Fix |
| :------------: | :------------: |
| image | image |
| image | image |

## Test
* Launch the simulation
```bash
roslaunch ow atacama_y1a.launch
```
* In another terminal (with OceanWATERS environment sourced) launch the **ow_exec** node with the `Demo.plx` plan:
```bash
roslaunch ow_plexil ow_exec.launch plan:=Demo.plx
```
* Verify that the following warning message is no longer emitted by the simulation whenever the _IdentifySampleLocation_ procedure is invoked: 
image
* Continue running the entire `Demo.plx` and verify no side effects are caused by this change
* Optional: Verify that the generated point cloud renders the colors correctly after the fix:
  - Launch the sim
  - In RVIZ: Add the PointCloud2 display as shown below:
image
  - Launch the **ow_exec** node with the `Demo.plx` plan
  - Observe that colors are correctly associated with generated point cloud as illustrated in the **Summary of Changes** section of this PR

### CODE REVIEW

**Comment by kmdalal** [comment]
How exactly do you get to the Rviz screen shown above, to select point cloud?

**Comment by Samahu** [comment]
> How exactly do you get to the Rviz screen shown above, to select point cloud?

I think you are looking for this button from the RVIZ window:
image
The rest is outlined in the optional verification step (make sure to zoom out a bit)

**Comment by kmdalal** [comment]
Ran the plan several times.  The RGB warnings of before are gone, but I have not yet seen a point cloud in Rviz.  I'm zoomed out far enough to see the entire grid.

**Comment by Samahu** [comment]
> Ran the plan several times. The RGB warnings of before are gone, but I have not yet seen a point cloud in Rviz. I'm zoomed out far enough to see the entire grid:
> 
> rviz

Only add the `/StereoCamera/points2/PointCloud2` topic when RVIZ loads and then run the `Demo.plx`. The point cloud should show once the camera points to the terrain and starts taking pictures.

**Comment by kmdalal** [comment]
Thanks for the last tip.  Finally I see the point clouds.  I think I was adding the wrong PointCloud2 before.

**Review by kmdalal — APPROVED** [review]
Works as described.

**Review by mogumbo — APPROVED** [review]
I don't actually approve of this solution. I'm just approving it because I've been outvoted and this is what the team wants to do for now. I hope we can find a solution later that keeps images at 16-bits, which is closer to what would probably be used on a real lander mission.

**Pull request merged**
