### PR TITLE
OCEANWATER-/833/834/835: address multiple issues within the ros action interface of the lander arm on ROS Noetic

### PR DESCRIPTION
**Pull request by Samahu**
## Linked Issues:
| EPIC ⚡ | [ N/A ] |
| :----------- | :----------- |
| Jira Ticket 🎟️ | [OCEANWATER-833 / update moveit syntax for noetic](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-833) |
| Jira Ticket 🎟️ | [OCEANWATER-834 / Arm actions fails to perform dig motions on ROS Noetic](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-834) |
| Jira Ticket 🎟️ | [OCEANWATER-835 / Dig Circular fails to perform when using non parallel move](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-835) |
| Github :octocat:  | builds on #187 |

## Summary of Changes
* All changes from #187 
* Address bug arm actions fails to perform dig motions on ROS Noetic
* Address bug "Dig Circular" fails to perform when using non parallel move
* Code cleanup:
  - Remove unused parameters of function `go_to_Z_coordinate_dig_circular`
  - Remove duplicate function `go_to_Z_coordinate` in `all_action_trajectories.py`

## Test
* Run [OceanWATERS Release 9 ROS Actions System Tests](https://babelfish.arc.nasa.gov/confluence/display/OCEANWATERS/OW-TEST-009-4+ROS+Actions)
  - When testing "Dig Ciruclar" try with the default settings first, then modify the `dig_circular_action_client.py` and select the following settings to test the non parallel dig circular motion too:
  ```python
    # # Default trenching values
    # goal.x_start = 1.65
    # goal.y_start = 0
    # goal.depth = 0.01
    # goal.parallel = True
    # goal.ground_position = constants.DEFAULT_GROUND_HEIGHT
    
    # General trenching values     
    goal.x_start = 1.55
    goal.y_start = 0.2 # also try with -0.2 and other values
    goal.depth = 0.045
    goal.parallel = False
    goal.ground_position = -0.155
  ```

### CODE REVIEW

**Review by mogumbo — APPROVED** [review]

**Comment by kmdalal** [comment]
Note that for alternate digging parameters, a corresponding grind must be done first, or else the scoop does not penetrate.

**Comment by kmdalal** [comment]
The alternate dig_circular given above seemed to look okay, but ended with errors:
```
$ ./dig_circular_action_client.py 
[INFO]: Result: final: 
  x: 0.5761914592724711
  y: 0.08682937436107961
  z: 0.24099045922874693
Exception in thread /DigCircular/feedback:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_pubsub.py", line 185, in robust_connect_subscriber
    conn.receive_loop(receive_cb)           
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 846, in receive_loop
    self.close()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 858, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'
```

**Comment by Samahu** [comment]
> The alternate dig_circular given above seemed to look okay, but ended with errors:
> 
> ```
> $ ./dig_circular_action_client.py 
> [INFO]: Result: final: 
>   x: 0.5761914592724711
>   y: 0.08682937436107961
>   z: 0.24099045922874693
> Exception in thread /DigCircular/feedback:
> Traceback (most recent call last):
>   File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
>     self.run()
>   File "/usr/lib/python3.8/threading.py", line 870, in run
>     self._target(*self._args, **self._kwargs)
>   File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_pubsub.py", line 185, in robust_connect_subscriber
>     conn.receive_loop(receive_cb)           
>   File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 846, in receive_loop
>     self.close()
>   File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 858, in close
>     self.socket.close()
> AttributeError: 'NoneType' object has no attribute 'close'
> ```

Is this error consistent? i.e. does it happen every time or is it a one time thing.
I don't think this error is related to the changes made.

**Comment by kmdalal** [comment]
It worked fine the second time.  Perhaps the error before was because there had previously been LCP errors resulting from doing a dig without a grind first.

**Review by kmdalal — APPROVED** [review]
If the dig_circular error I reported is unrelated, then this looks good!

**Pull request merged**
