### PR TITLE
Oceanwater 1058 & 1071 - rostest Improvements and Expected Value Automation

### PR DESCRIPTION
**Pull request by AstroStucky**
## Linked Issues:
| EPIC ⚡ | [OCEANWATER-983](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-983) |
| :----------- | :----------- |
| Jira Ticket 🎟️ | [OCEANWATER-1058](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-1058) <br/> [OCEANWATER-1071](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-1071)|

## Summary of Changes
* **terrain_interaction.test** changed name to **sample_collection.test**
* Added the new discard arm action to the arm_check_action test.
* **action_test_analysis.py** script added to facilitate the computation of the most statistically correct expected values for action testing.
* Common functions between **sample_collection.py** and **arm_check_action.py** were re-organized into a python module that they both import. 
  * Those common functions were modified to make use of the output from the **action_test_analysis.py** script for the purpose of comparing tests results to expected values.
* Added an option to both action calling tests that disables checks for action durations and checks for arm final positions. This facilitates the **action_test_analysis.py** script to run its own tests and act as an observer of action outcome.
* Test scripts now override the proper unittest class methods for initial test setup.
* Unrelated change made in **action_trajectories.py** that requires a variable to not be None type before accessing a member variable (this may just be a work around for a bug).

## Test 1 - Run rostests
1. Run the arm_check_action test
`rostest ow_sim_tests arm_check_action.test`
2. Run the sample_collection test
`rostest ow_sim_tests sample_collection.test`
3. Report any failures that occur in either test here. 
**Note** Due to bugs in both the regolith system and arm control these tests will sometimes fail, and those failures may not necessarily be due to this PR. If anything fails, share test output here, so I can help interpret what happened.
5. Rerun tests as many times as you like. 

## Test 2 - Run Test Anlysis Script 
1. Change directory to **ow_sim_tests**
2. Print the script's help message
`./script/action_test_analysis.py --help`
4. Call the test analysis script for either the arm_check_action or sample_collection tests.
e.g. `./script/action_test_analysis.py arm_check_action.test 3 --show-gzclient`
When the script completes, it will overwrite the corresponding YAML in `ow_sim_tests/config` for the test you ran the script for. This is fine. Take a look at the YAML to understand the output it generates. If you need to get the previous output back, you can call `git checkout config`

### CODE REVIEW

**Comment by AstroStucky** [comment]
@anjan1984 I do not wish to take you away from more important tasks you are already working right now, but I was hoping you could provide a review of only the changes in **action_trajectories.py**. This fixes a sporadic bug I encountered that results in the following AttributeError
```
AttributeError: 'NoneType' object has no attribute 'joint_trajectory'
```

**Comment by AstroStucky** [comment]
@kmdalal This should be enough context. Did you additionally observe any strange behavior during the dig linear activity or see any errors you aren't used to seeing in the simulator output? If you are unsure whether you can answer these questions from your own read of the output, you're always welcome to attach the log file here, and that goes for all reviewers. 

Seeing how close the expected duration is to the mean duration of the test, it's clear right of the bat that the minimum duration tolerance was not implemented right. I'll take a look and should have a fix shortly.

**Comment by AstroStucky** [comment]
I was right in my previous post. The max duration was being computed wrong. This is now fixed. @kmdalal @anthonykoutroulis, please resume testing.

**Review by kmdalal — APPROVED** [review]
I tried all the tests (*.test files) once each, and they all passed.  My code review was light, mainly for readability.  Looks good!

**Review by anthonykoutroulis — APPROVED** [review]

**Pull request merged**
